### ISSUE TITLE
this.proxy请求

### ISSUE THREAD

**Issue by sg513017** [xiongwilee/koa-grace#22]
我要post一串xml给后台服务器，但我发现你的配置项里只支持form啊，header也不能配置

**Comment by xiongwilee** [comment]
可以在proxy的时候配置：
```
yield this.proxy('test:test/test',{
conf: {
// 这个配置就是request的配置 , 参考：https://github.com/request/request#requestoptions-callback
}
})
```

**Comment by sg513017** [comment]
我是这么写的：
await this.proxy({api: 'api:post:test/test'},
        {
            conf : { 'content-type': 'text/plain;charset=UTF-8' },
            form : xml
        });
    console.log(this.backData.api);
我又把json改为false, 然后发起请求，可是出现了下面的错误：
Error: write after end
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:439:15)
    at Request.write (/home/ubuntu/membership_sevice/node_modules/request/request.js:1424:27)
    at end (/home/ubuntu/membership_sevice/node_modules/request/request.js:551:18)
    at Immediate.<anonymous> (/home/ubuntu/sevice/node_modules/request/request.js:580:7)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5) status: 'NULL', duration: '36ms' }
