### ISSUE TITLE
模板引擎改为 nunjucks 出现找不到模板错误

### ISSUE THREAD

**Issue by JeffreyChu** [xiongwilee/koa-grace#41]
结合了 grace-vue-webpack-boilerplate
views 目录结构为初始目录结构
views
-- _common
----hook
----layout.html
----...
--home
----index.html

views/home/index.html 内容
```html
{% extends "../_common/layout.html" %}
...
```
报错信息：
```javascript
[nodemon] changes after filters (before/after): 1/0
  koa-router GET /home +7m
  koa-router dispatch /home /^\/home(?:\/(?=$))?$/i +0ms
Unhandled rejection Template render error: (unknown path)
  Error: template not found: ../_common/layout.html
    at Object.exports.prettifyError (/Users/jeff/Code/new-wap/server/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/jeff/Code/new-wap/server/node_modules/nunjucks/src/environment.js:489:31
```
居然找不到 layout.html，看路径是没错啊 😱   
另模板引擎改回 swiger 便不会报错 😳

**Comment by xiongwilee** [comment]
可以参考下 https://github.com/xiongwilee/iblog 下nunjucks的使用
