### ISSUE TITLE
Cannot find module 'is-generator-function' while I am runing npm install && npm run dev

### ISSUE THREAD

**Issue by sharmine** [xiongwilee/koa-grace#47]
The error message is showing below:

[nodemon] watching: app/*/controller/**/* app/*/model/**/* app/*/mock/**/*
[nodemon] watching extensions: js,json
[nodemon] starting `node bin/server.js`
[nodemon] child pid: 20632
[nodemon] watching 342 files
module.js:487
    throw err;
    ^

Error: Cannot find module 'is-generator-function'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\git\koa-grace\node_modules\_koa@2.3.0@koa\lib\application.js:8:29)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\git\koa-grace\src\app.js:4:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
[nodemon] app crashed - waiting for file changes before starting...

Thanks.

**Comment by sharmine** [comment]
node version v8.2.1

**Comment by xiongwilee** [comment]
`is-generator-function`是koa自己的依赖，你是不是没有`npm install`或者手误删了这个依赖？

可以`npm install is-generator-function`试试
